## Numpy Functions list 


In [32]:
import numpy as np

In [33]:
lst = np.array([1,2,3])

In [34]:
lst

array([1, 2, 3])

# Make an array 
    ## using numpy we can create an array from diffrent method the
    - Conservation from the other python(tuple,list)
    - Intrinsic numpy array creation objects (arnage, ones,zeros)
    - Reading arrays from the disk either from standrd customs format
    - Creating arrays from the raw bytes throuh the use of string or buffers
    - Use of special library functions (random)

## array using list

In [35]:
lst = np.array([1,2,3,4,5])

In [36]:
lst

array([1, 2, 3, 4, 5])

In [37]:
lstarray = np.array([[1,2,3],[6,7,8],[5,8,7]])

In [38]:
lstarray

array([[1, 2, 3],
       [6, 7, 8],
       [5, 8, 7]])

In [39]:
## array data type


In [40]:
lstarray.dtype

dtype('int32')

In [41]:
## check the shape etc

In [42]:
lstarray.shape

(3, 3)

In [43]:
# array size
lstarray.size

9

## Intrinsic numpy array creation objects (arnage, ones,zeros)

In [44]:
# it creates array of 2*5 of zeros 2rows 5 cols
zeros = np.zeros((2,5))

In [45]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# range function to make array, its create array written in the function
rng = np.arange(15)

In [47]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
#it creates equally and lineary divied the number
lspace = np.linspace(1,5,11)

In [49]:
lspace

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [50]:
# empty create empty array
emp = np.empty((3,3))

In [51]:
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.67187361e-321],
       [8.90103559e-307, 1.24611470e-306, 4.45063578e-308]])

In [52]:
# empty like make a copy of your assigned array size
em_like = np.empty_like(lspace)

In [53]:
em_like

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [54]:
# identity make an identiry matrix\
ide = np.identity(5)

In [55]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
ide.shape

(5, 5)

In [57]:

arr = np.arange(99)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
# reshape your array to dimenstions
arr = arr.reshape(3,33)

In [60]:
# revel is used to restore an array into one
arr = arr.ravel()

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.shape

(99,)

In [63]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [64]:
ar = np.array(x)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

## axis = 0 means you can get the value in cols like here abouve there are 3 cols and 3 rows you can calculate them in axis0 mean you can calculate cols and axis 1 mean you can calculate as a row

In [66]:
ar.sum(axis=0)

array([12,  8,  9])

In [67]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [68]:
## T can take transpose of the array it converts rows to cols
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
# ndim represents the number of dimensions (axes) of the ndarray. shape is a tuple of integers
# representing the size of the ndarray in each dimension. size is the total number of elements in the ndarray.
ar.ndim

2

In [70]:
# size of array how much elements in your array
ar.size

9

In [71]:
# size that are take pls in memory
ar.nbytes

36

In [72]:
one = np.array([1,3,4,643,2])

In [74]:
# use this method to get the max number of index that can store the large value of your array element
one.argmax()

3

In [75]:
# use this to get arrays minimum value of index
one.argmin()

0

In [79]:
# use this function to get sorted list of index of your array
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
ar2 = np.array([[1,2,1],[4,0,6],[15,2,0]])

In [82]:
ar2

array([[ 1,  2,  1],
       [ 4,  0,  6],
       [15,  2,  0]])

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22,  3,  0]])

In [85]:
ar * ar2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,   2,   0]])

In [86]:
# take sqrt of your array
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
# check the gratter value in return index type location that on which number is your element gratter
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [89]:
# to check non zero elements in your array
np.count_nonzero(ar)

8